Caption_templates = [
    "Describe the abnormalities in this spinal MRI.",
    "What are the key findings in this scan?",
    "Summarize the MRI observations.",
    "What degenerative changes are present in this MRI?",
    "What is the most concerning feature of this MRI?",
    "What notable changes can be observed in this spinal MRI?",
    "Provide an overall assessment of this spinal MRI.",
    "What clinical significance do the findings in this MRI have?",
    "Caption the findings in this medical image?",
    "Describe the findings you see.",
    "Caption this medical scan's findings.",
    "What are the findings here?",
    "Describe these findings.",
    "Summarize the findings in these images.",
    "Caption this scan's findings.",
    "Summarize the findings of this MRI.",
    "Generate a medical report based on this image.",
    "Can you provide a diagnosis based on this image?",
    ]
CapSeg_templates = [
            "Please answer and segment.",
            "Please output segmentation mask and answer.",
            "Please answer and segment based on the above description.",
            "Please answer and segment based on the above definition.",
            "Can you answer and segment it based on the above description or definition.",
            "Please output segmentation mask and answer based on the above description or definition.",
            "Please segment accordingly.",
            "Please provide segmentation and answer according to it.",
            "Now, segment it and provide your answer.",
            "Please segment and provide your response.",
            "Can you segment it accordingly?",
       ]